### ISSUE TITLE
snakemake --snakefile ERROR: (exited with non-zero exit code)

### ISSUE THREAD

**Issue by sen1019san** [giesselmann/nanopype#16]
Hello, I had a problem when I configured the software following the Installation Source guide command:
snakemake --snakefile path/to/install.smk --directory [INSTALL_PREFIX] all -j 8 --config threads_build=8
The ERROR reture as " (exited with non-zero exit code)".
How can I fit the problem?

**Comment by sen1019san** [comment]
Hello, I implemented the command:
snakemake --snakefile rules/install.smk --directory [INSTALL_PREFIX] all -j [8] --config threads_build=8
And this is the ERROR log file.
[2020-08-03T143936.995992.snakemake.log](https://github.com/giesselmann/nanopype/files/5014415/2020-08-03T143936.995992.snakemake.log)

**Comment by giesselmann** [comment]
Hi,
can you post the stdout/stderr for that command, the log doesn't tell much for the install commands.
Maybe also first try sth. like:
>snakemake --snakefile rules/install.smk --directory [INSTALL_PREFIX] graphmap

To disable parallel build and start with graphmap again (the rule order is random if you run all).
Pay

**Comment by sen1019san** [comment]
Thanks, Pay! I tried the command:
snakemake --snakefile rules/install.smk --directory [INSTALL_PREFIX] graphmap
And it still returned ERROR. This is the stderr file.
[log.txt](https://github.com/giesselmann/nanopype/files/5020185/log.txt)

**Comment by giesselmann** [comment]
Ah, I see:
For the source installation you need a basic c/c++ toolchain set up.
The system libraries required are listed at the beginning of https://nanopype.readthedocs.io/en/latest/installation/src/
Additionally you need (names as in ubuntu 18.04):
* python-minimal python3-dev
* wget rsync
* git gcc g++
* binutils autoconf make cmake
* libcunit1-dev libhdf5-dev libopenblas-dev

for building tools from source.

I'll add that to the source installation docs...

**Comment by giesselmann** [comment]
I found an error in the source installation of some (python) tools.
This is fixed in v1.0.1, please update your installation to get the src build running.

Pay

**Comment by giesselmann** [comment]
Hi @sen1019san

any updates on this?
