### ISSUE TITLE
Problem with install flappie

### ISSUE THREAD

**Issue by NguyenLePhuong** [giesselmann/nanopype#4]
Hi,

I am trying to install flappie in ubuntu 16.04, I followed the instructions, but there are some errors:
(base) (katuali) leo@leo:~/NGS/katuali/flappie/flappie$ make
cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DHDF5_ROOT='' && \
make flappie
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leo/NGS/katuali/flappie/flappie/build
make[1]: Entering directory '/home/leo/NGS/katuali/flappie/flappie/build'
make[2]: Entering directory '/home/leo/NGS/katuali/flappie/flappie/build'
make[3]: Entering directory '/home/leo/NGS/katuali/flappie/flappie/build'
make[4]: Entering directory '/home/leo/NGS/katuali/flappie/flappie/build'
make[4]: Leaving directory '/home/leo/NGS/katuali/flappie/flappie/build'
make[4]: Entering directory '/home/leo/NGS/katuali/flappie/flappie/build'
[  7%] Building C object CMakeFiles/flappie_objects.dir/src/networks.c.o
In file included from /home/leo/NGS/katuali/flappie/flappie/src/networks.c:10:0:
/home/leo/NGS/katuali/flappie/flappie/src/models/flipflop_r941native.h:1:1: error: unknown type name ‘version’
 version https://git-lfs.github.com/spec/v1
 ^
/home/leo/NGS/katuali/flappie/flappie/src/models/flipflop_r941native.h:1:14: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 version https://git-lfs.github.com/spec/v1
              ^
/home/leo/NGS/katuali/flappie/flappie/src/models/flipflop_r941native.h:2:12: error: invalid suffix "dd6adb73a55d95014a6701658d399069b144451dff9179cbefbfb39bb230e" on integer constant
 oid sha256:418dd6adb73a55d95014a6701658d399069b144451dff9179cbefbfb39bb230e
            ^
In file included from /home/leo/NGS/katuali/flappie/flappie/src/networks.c:11:0:
/home/leo/NGS/katuali/flappie/flappie/src/models/flipflop_r941native5mC.h:2:12: error: invalid suffix "bffdb61b0389174ce2be46ff2e41ae9efaf1332fef6638b8b8e41cf67838" on integer constant
 oid sha256:2015bffdb61b0389174ce2be46ff2e41ae9efaf1332fef6638b8b8e41cf67838
            ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:160:16: error: ‘_conv_rnnrf_flipflop_r941native_W’ undeclared here (not in a function)
     .conv_W = &_conv_rnnrf_flipflop_r941native_W,
                ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:161:16: error: ‘_conv_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .conv_b = &_conv_rnnrf_flipflop_r941native_b,
                ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:162:20: error: ‘conv_rnnrf_flipflop_r941native_stride’ undeclared here (not in a function)
     .conv_stride = conv_rnnrf_flipflop_r941native_stride,
                    ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:165:18: error: ‘_gruB1_rnnrf_flipflop_r941native_iW’ undeclared here (not in a function)
     .gruB1_iW = &_gruB1_rnnrf_flipflop_r941native_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:166:18: error: ‘_gruB1_rnnrf_flipflop_r941native_sW’ undeclared here (not in a function)
     .gruB1_sW = &_gruB1_rnnrf_flipflop_r941native_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:167:17: error: ‘_gruB1_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .gruB1_b = &_gruB1_rnnrf_flipflop_r941native_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:169:18: error: ‘_gruF2_rnnrf_flipflop_r941native_iW’ undeclared here (not in a function)
     .gruF2_iW = &_gruF2_rnnrf_flipflop_r941native_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:170:18: error: ‘_gruF2_rnnrf_flipflop_r941native_sW’ undeclared here (not in a function)
     .gruF2_sW = &_gruF2_rnnrf_flipflop_r941native_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:171:17: error: ‘_gruF2_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .gruF2_b = &_gruF2_rnnrf_flipflop_r941native_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:173:18: error: ‘_gruB3_rnnrf_flipflop_r941native_iW’ undeclared here (not in a function)
     .gruB3_iW = &_gruB3_rnnrf_flipflop_r941native_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:174:18: error: ‘_gruB3_rnnrf_flipflop_r941native_sW’ undeclared here (not in a function)
     .gruB3_sW = &_gruB3_rnnrf_flipflop_r941native_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:175:17: error: ‘_gruB3_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .gruB3_b = &_gruB3_rnnrf_flipflop_r941native_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:177:18: error: ‘_gruF4_rnnrf_flipflop_r941native_iW’ undeclared here (not in a function)
     .gruF4_iW = &_gruF4_rnnrf_flipflop_r941native_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:178:18: error: ‘_gruF4_rnnrf_flipflop_r941native_sW’ undeclared here (not in a function)
     .gruF4_sW = &_gruF4_rnnrf_flipflop_r941native_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:179:17: error: ‘_gruF4_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .gruF4_b = &_gruF4_rnnrf_flipflop_r941native_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:181:18: error: ‘_gruB5_rnnrf_flipflop_r941native_iW’ undeclared here (not in a function)
     .gruB5_iW = &_gruB5_rnnrf_flipflop_r941native_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:182:18: error: ‘_gruB5_rnnrf_flipflop_r941native_sW’ undeclared here (not in a function)
     .gruB5_sW = &_gruB5_rnnrf_flipflop_r941native_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:183:17: error: ‘_gruB5_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .gruB5_b = &_gruB5_rnnrf_flipflop_r941native_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:185:14: error: ‘_FF_rnnrf_flipflop_r941native_W’ undeclared here (not in a function)
     .FF_W = &_FF_rnnrf_flipflop_r941native_W,
              ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:186:14: error: ‘_FF_rnnrf_flipflop_r941native_b’ undeclared here (not in a function)
     .FF_b = &_FF_rnnrf_flipflop_r941native_b
              ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:192:16: error: ‘_conv_rnnrf_flipflop_r941native5mC_W’ undeclared here (not in a function)
     .conv_W = &_conv_rnnrf_flipflop_r941native5mC_W,
                ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:193:16: error: ‘_conv_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .conv_b = &_conv_rnnrf_flipflop_r941native5mC_b,
                ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:194:20: error: ‘conv_rnnrf_flipflop_r941native5mC_stride’ undeclared here (not in a function)
     .conv_stride = conv_rnnrf_flipflop_r941native5mC_stride,
                    ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:197:18: error: ‘_gruB1_rnnrf_flipflop_r941native5mC_iW’ undeclared here (not in a function)
     .gruB1_iW = &_gruB1_rnnrf_flipflop_r941native5mC_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:198:18: error: ‘_gruB1_rnnrf_flipflop_r941native5mC_sW’ undeclared here (not in a function)
     .gruB1_sW = &_gruB1_rnnrf_flipflop_r941native5mC_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:199:17: error: ‘_gruB1_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .gruB1_b = &_gruB1_rnnrf_flipflop_r941native5mC_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:201:18: error: ‘_gruF2_rnnrf_flipflop_r941native5mC_iW’ undeclared here (not in a function)
     .gruF2_iW = &_gruF2_rnnrf_flipflop_r941native5mC_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:202:18: error: ‘_gruF2_rnnrf_flipflop_r941native5mC_sW’ undeclared here (not in a function)
     .gruF2_sW = &_gruF2_rnnrf_flipflop_r941native5mC_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:203:17: error: ‘_gruF2_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .gruF2_b = &_gruF2_rnnrf_flipflop_r941native5mC_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:205:18: error: ‘_gruB3_rnnrf_flipflop_r941native5mC_iW’ undeclared here (not in a function)
     .gruB3_iW = &_gruB3_rnnrf_flipflop_r941native5mC_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:206:18: error: ‘_gruB3_rnnrf_flipflop_r941native5mC_sW’ undeclared here (not in a function)
     .gruB3_sW = &_gruB3_rnnrf_flipflop_r941native5mC_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:207:17: error: ‘_gruB3_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .gruB3_b = &_gruB3_rnnrf_flipflop_r941native5mC_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:209:18: error: ‘_gruF4_rnnrf_flipflop_r941native5mC_iW’ undeclared here (not in a function)
     .gruF4_iW = &_gruF4_rnnrf_flipflop_r941native5mC_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:210:18: error: ‘_gruF4_rnnrf_flipflop_r941native5mC_sW’ undeclared here (not in a function)
     .gruF4_sW = &_gruF4_rnnrf_flipflop_r941native5mC_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:211:17: error: ‘_gruF4_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .gruF4_b = &_gruF4_rnnrf_flipflop_r941native5mC_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:213:18: error: ‘_gruB5_rnnrf_flipflop_r941native5mC_iW’ undeclared here (not in a function)
     .gruB5_iW = &_gruB5_rnnrf_flipflop_r941native5mC_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:214:18: error: ‘_gruB5_rnnrf_flipflop_r941native5mC_sW’ undeclared here (not in a function)
     .gruB5_sW = &_gruB5_rnnrf_flipflop_r941native5mC_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:215:17: error: ‘_gruB5_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .gruB5_b = &_gruB5_rnnrf_flipflop_r941native5mC_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:217:14: error: ‘_FF_rnnrf_flipflop_r941native5mC_W’ undeclared here (not in a function)
     .FF_W = &_FF_rnnrf_flipflop_r941native5mC_W,
              ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:218:14: error: ‘_FF_rnnrf_flipflop_r941native5mC_b’ undeclared here (not in a function)
     .FF_b = &_FF_rnnrf_flipflop_r941native5mC_b
              ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:224:16: error: ‘_conv_rnnrf_flipflop_r10Cpcr_W’ undeclared here (not in a function)
     .conv_W = &_conv_rnnrf_flipflop_r10Cpcr_W,
                ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:225:16: error: ‘_conv_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .conv_b = &_conv_rnnrf_flipflop_r10Cpcr_b,
                ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:226:20: error: ‘conv_rnnrf_flipflop_r10Cpcr_stride’ undeclared here (not in a function)
     .conv_stride = conv_rnnrf_flipflop_r10Cpcr_stride,
                    ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:229:18: error: ‘_gruB1_rnnrf_flipflop_r10Cpcr_iW’ undeclared here (not in a function)
     .gruB1_iW = &_gruB1_rnnrf_flipflop_r10Cpcr_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:230:18: error: ‘_gruB1_rnnrf_flipflop_r10Cpcr_sW’ undeclared here (not in a function)
     .gruB1_sW = &_gruB1_rnnrf_flipflop_r10Cpcr_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:231:17: error: ‘_gruB1_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .gruB1_b = &_gruB1_rnnrf_flipflop_r10Cpcr_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:233:18: error: ‘_gruF2_rnnrf_flipflop_r10Cpcr_iW’ undeclared here (not in a function)
     .gruF2_iW = &_gruF2_rnnrf_flipflop_r10Cpcr_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:234:18: error: ‘_gruF2_rnnrf_flipflop_r10Cpcr_sW’ undeclared here (not in a function)
     .gruF2_sW = &_gruF2_rnnrf_flipflop_r10Cpcr_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:235:17: error: ‘_gruF2_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .gruF2_b = &_gruF2_rnnrf_flipflop_r10Cpcr_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:237:18: error: ‘_gruB3_rnnrf_flipflop_r10Cpcr_iW’ undeclared here (not in a function)
     .gruB3_iW = &_gruB3_rnnrf_flipflop_r10Cpcr_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:238:18: error: ‘_gruB3_rnnrf_flipflop_r10Cpcr_sW’ undeclared here (not in a function)
     .gruB3_sW = &_gruB3_rnnrf_flipflop_r10Cpcr_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:239:17: error: ‘_gruB3_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .gruB3_b = &_gruB3_rnnrf_flipflop_r10Cpcr_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:241:18: error: ‘_gruF4_rnnrf_flipflop_r10Cpcr_iW’ undeclared here (not in a function)
     .gruF4_iW = &_gruF4_rnnrf_flipflop_r10Cpcr_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:242:18: error: ‘_gruF4_rnnrf_flipflop_r10Cpcr_sW’ undeclared here (not in a function)
     .gruF4_sW = &_gruF4_rnnrf_flipflop_r10Cpcr_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:243:17: error: ‘_gruF4_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .gruF4_b = &_gruF4_rnnrf_flipflop_r10Cpcr_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:245:18: error: ‘_gruB5_rnnrf_flipflop_r10Cpcr_iW’ undeclared here (not in a function)
     .gruB5_iW = &_gruB5_rnnrf_flipflop_r10Cpcr_iW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:246:18: error: ‘_gruB5_rnnrf_flipflop_r10Cpcr_sW’ undeclared here (not in a function)
     .gruB5_sW = &_gruB5_rnnrf_flipflop_r10Cpcr_sW,
                  ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:247:17: error: ‘_gruB5_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .gruB5_b = &_gruB5_rnnrf_flipflop_r10Cpcr_b,
                 ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:249:14: error: ‘_FF_rnnrf_flipflop_r10Cpcr_W’ undeclared here (not in a function)
     .FF_W = &_FF_rnnrf_flipflop_r10Cpcr_W,
              ^
/home/leo/NGS/katuali/flappie/flappie/src/networks.c:250:14: error: ‘_FF_rnnrf_flipflop_r10Cpcr_b’ undeclared here (not in a function)
     .FF_b = &_FF_rnnrf_flipflop_r10Cpcr_b
              ^
CMakeFiles/flappie_objects.dir/build.make:88: recipe for target 'CMakeFiles/flappie_objects.dir/src/networks.c.o' failed
make[4]: *** [CMakeFiles/flappie_objects.dir/src/networks.c.o] Error 1
make[4]: Leaving directory '/home/leo/NGS/katuali/flappie/flappie/build'
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/flappie_objects.dir/all' failed
make[3]: *** [CMakeFiles/flappie_objects.dir/all] Error 2
make[3]: Leaving directory '/home/leo/NGS/katuali/flappie/flappie/build'
CMakeFiles/Makefile2:158: recipe for target 'CMakeFiles/flappie.dir/rule' failed
make[2]: *** [CMakeFiles/flappie.dir/rule] Error 2
make[2]: Leaving directory '/home/leo/NGS/katuali/flappie/flappie/build'
Makefile:223: recipe for target 'flappie' failed
make[1]: *** [flappie] Error 2
make[1]: Leaving directory '/home/leo/NGS/katuali/flappie/flappie/build'
Makefile:30: recipe for target 'build/flappie' failed
make: *** [build/flappie] Error 2

When you have time, could you give me the solutions, thank you in advance,

Best regards, 
Leo

**Comment by giesselmann** [comment]
Hey, looks like you build Flappie manually inside the katuali environment?
From the output it's hard to give advise, since I read 'git-lfs' in the error message, is git-lfs properly set up?
Also have you tried installing Flappi with the provided snakemake rules e.g from within the nanopype repository:

> snakemake --snakefile rules/install.smk --directory /path/to/INSTALL_PREFIX flappie

This should build and install Flappie into /path/to/INSTALL_PREFIX/bin/flappie

Best,
Pay
