### ISSUE TITLE
Nanopype on Mac OS 10.14 (Albacore "deprecated")

### ISSUE THREAD

**Issue by md342010** [giesselmann/nanopype#6]
Hi,

Thanks for having implemented a such pipeline. We would like to test it with our data but our computer are under Mac OS 10.14. But Albacore can't be installed on Mas OS 10.14 and it's archived by ONT. If I want to use it, I must create a virtual machine. I don't see if we can use Albacore software with our flowcell, recent or in the future.
So do you think adapt Nanopype with only guppy ? Thanks a lot for your answer.
Regards,
Emmanuelle

**Comment by giesselmann** [comment]
Hi Emmanuelle,
Guppy is the standard basecaller of Nanopype. Albacore works if you have an installation of it, but I wouldn't recommend using it anymore. 
The basecaller docs are here: https://nanopype.readthedocs.io/en/latest/rules/basecalling/
Not sure if I understood your question correctly and if this helps.
Pay
